# Generated by Django 5.0.6 on 2024-06-14 15:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='السنة الدراسية')),
            ],
            options={
                'verbose_name': 'السنة',
                'verbose_name_plural': '  السنة الدراسية',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='المادة الدراسية')),
                ('source', models.CharField(choices=[('وزارة التربية والتعليم', 'وزارة التربية والتعليم'), ('مورد خارجي', 'مورد خارجي')], max_length=50, verbose_name='مصدر التوريد')),
                ('received_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية الواردة')),
                ('available_quantity', models.PositiveIntegerField(verbose_name='الكمية المتاحة')),
                ('term', models.CharField(choices=[('الترم الأول', 'الترم الأول'), ('الترم الثاني', 'الترم الثاني')], max_length=20, verbose_name='الترم الدراسي')),
                ('received_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الاستلام')),
            ],
            options={
                'verbose_name': 'كتاب دراسي',
                'verbose_name_plural': 'المواد الدراسية',
            },
        ),
        migrations.CreateModel(
            name='NotebookType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع الكراسة')),
                ('size', models.CharField(max_length=50, verbose_name='حجم الكراسة')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='وصف الكراسة')),
                ('source', models.CharField(choices=[('وزارة التربية والتعليم', 'وزارة التربية والتعليم'), ('مورد خارجي', 'مورد خارجي')], max_length=50, verbose_name='مصدر التوريد')),
                ('in_quantity', models.IntegerField(default=0, verbose_name='الكمية الواردة')),
                ('live_quantity', models.IntegerField(default=0, verbose_name='الكمية الحالية')),
                ('received_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الاستلام')),
            ],
            options={
                'verbose_name': 'نوع كراسة',
                'verbose_name_plural': 'أنواع الكراسات',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المورد')),
                ('phone', models.CharField(max_length=15, verbose_name='رقم تليفون المورد')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردين',
            },
        ),
        migrations.CreateModel(
            name='BookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='الكمية المستلمة')),
                ('received_date', models.DateField(verbose_name='تاريخ التوريد')),
                ('book_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.book', verbose_name='المادة الدراسية')),
            ],
            options={
                'verbose_name': ' اضافة توريد كتب ',
                'verbose_name_plural': ' اضافة توريد كتب ',
            },
        ),
        migrations.CreateModel(
            name='BookDepreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية المستهلكة')),
                ('cause', models.CharField(max_length=100, verbose_name='سبب الإهلاك')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ الإهلاك')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.book', verbose_name='الكتاب')),
            ],
            options={
                'verbose_name': 'إهلاك كتاب',
                'verbose_name_plural': 'إهلاك الكتب',
            },
        ),
        migrations.CreateModel(
            name='BookOutstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المستلم')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية ')),
                ('date', models.DateField(verbose_name='تاريخ الصرف')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.book', verbose_name='الكتاب')),
            ],
            options={
                'verbose_name': 'صرف كتاب',
                'verbose_name_plural': 'صرف الكتب',
            },
        ),
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('تمهيدى', 'تمهيدى'), ('KG1', 'KG1'), ('KG2', 'KG2'), ('PRIM 1', 'الصف  الأول الابتدائي '), ('PRIM 2', 'الصف الابتدائي الثاني'), ('PRIM 3', 'الصف الابتدائي الثالث'), ('PRIM 4', 'الصف الابتدائي الرابع'), ('PRIM 5', 'الصف الابتدائي الخامس'), ('PRIM 6', 'الصف الابتدائي السادس'), ('PREP 1', 'الصف الاعدادى الأول'), ('PREP 2', 'الصف الثاني الاعدادى '), ('PREP 3', 'الصف الثالث الاعدادى '), ('SEC 1', 'الصف الأول الثانوي '), ('SEC 2', 'الصف الثاني الثانوي '), ('SEC 3', 'الصف الثالث الثانوي ')], max_length=50, verbose_name='اسم الصف الدراسي')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.academicyear', verbose_name='السنة الدراسية')),
            ],
            options={
                'verbose_name': 'الصف',
                'verbose_name_plural': 'الصف الدراسي',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.classlevel', verbose_name='الصف الدراسي'),
        ),
        migrations.CreateModel(
            name='NotebookDepreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية المستهلكة')),
                ('cause', models.CharField(max_length=100, verbose_name='سبب الإهلاك')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ الإهلاك')),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.notebooktype', verbose_name='الكراسات')),
            ],
            options={
                'verbose_name': 'إهلاك الكراسات',
                'verbose_name_plural': 'إهلاك الكراسات',
            },
        ),
        migrations.CreateModel(
            name='NotebookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='الكمية المستلمة')),
                ('received_date', models.DateField(verbose_name='تاريخ التوريد')),
                ('notebook_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.notebooktype', verbose_name='نوع الكراسة')),
            ],
            options={
                'verbose_name': 'توريد كراسة',
                'verbose_name_plural': 'توريدات الكراسات',
            },
        ),
        migrations.CreateModel(
            name='SchoolBooklet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان البوكليت')),
                ('booklet_edition', models.CharField(blank=True, max_length=20, null=True, verbose_name='إصدار الكتاب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف البوكليت')),
                ('source', models.CharField(choices=[('وزارة التربية والتعليم', 'وزارة التربية والتعليم'), (' مدرسة المنار', 'مدرسة المنار'), ('مورد خارجي', 'مورد خارجي')], max_length=50, verbose_name='مصدر التوريد')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية الواردة')),
                ('live_quantity', models.IntegerField(default=0, verbose_name='الكمية الحالية')),
                ('term', models.CharField(choices=[('الترم الأول', 'الترم الأول'), ('الترم الثاني', 'الترم الثاني')], max_length=20, verbose_name='الترم الدراسي')),
                ('received_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الاستلام')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.classlevel', verbose_name='الصف الدراسي')),
            ],
            options={
                'verbose_name': 'بوكليت مدرسي',
                'verbose_name_plural': 'البوكليتات المدرسية',
            },
        ),
        migrations.CreateModel(
            name='BookletDepreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية المستهلكة')),
                ('cause', models.CharField(max_length=100, verbose_name='سبب الإهلاك')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ الإهلاك')),
                ('booklet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.schoolbooklet', verbose_name='البوكليت')),
            ],
            options={
                'verbose_name': 'إهلاك البوكليت',
                'verbose_name_plural': 'إهلاك البوكليت',
            },
        ),
        migrations.CreateModel(
            name='BookletDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية المستلمة')),
                ('received_date', models.DateField(verbose_name='تاريخ التوريد')),
                ('booklet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.schoolbooklet', verbose_name='نوع البوكليت')),
            ],
            options={
                'verbose_name': 'تفاصيل توريد البوكليت',
                'verbose_name_plural': 'تفاصيل توريد البوكليت',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('تمهيدى', 'تمهيدى'), ('رياض الأطفال', 'رياض الأطفال'), ('primry', 'primry'), ('الاعدادية', 'الاعدادية'), ('الثانوية', 'الثانوية')], max_length=50, verbose_name='المرحلة الدراسية')),
            ],
            options={
                'verbose_name': 'المرحلة',
                'verbose_name_plural': 'المراحل الدراسية',
                'unique_together': {('stage',)},
            },
        ),
        migrations.AddField(
            model_name='schoolbooklet',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.stage', verbose_name='المرحلة الدراسية'),
        ),
        migrations.CreateModel(
            name='NotebookAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_assignment', models.PositiveIntegerField(default=0, verbose_name='الكمية المخصصة')),
                ('term', models.CharField(choices=[('الترم الأول', 'الترم الأول'), ('الترم الثاني', 'الترم الثاني')], max_length=20, verbose_name='الترم الدراسي')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التخصيص')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.classlevel', verbose_name='الصف الدراسي')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.academicyear', verbose_name='السنة الدراسية')),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.notebooktype', verbose_name='الكراسة')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.stage', verbose_name='المرحلة الدراسية')),
            ],
            options={
                'verbose_name': 'تخصيص كراسة',
                'verbose_name_plural': 'تخصيصات الكراسات',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, verbose_name='الفصل الدراسي')),
                ('class_levels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.classlevel', verbose_name='الصف الدراسي')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.stage', verbose_name='المرحلة')),
            ],
            options={
                'verbose_name': 'ترقيم الفصول',
                'verbose_name_plural': 'الفصل الدراسي',
                'unique_together': {('class_levels', 'name')},
            },
        ),
        migrations.AddField(
            model_name='classlevel',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.stage', verbose_name='المرحلة'),
        ),
        migrations.AddField(
            model_name='book',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.stage', verbose_name='المرحلة الدراسية'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الطالب')),
                ('national_id', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_national_id', message='يجب أن يحتوي الرقم القومي على 14 رقمًا بدقة.', regex='^\\d{14}$')], verbose_name='الرقم القومي')),
                ('phone_number', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='store.academicyear', verbose_name='السنة الدراسية')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.classlevel', verbose_name='الصف الدراسي')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.classroom', verbose_name='الفصل الدراسي')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.stage', verbose_name='المرحلة الدراسية')),
            ],
            options={
                'verbose_name': 'الطالب',
                'verbose_name_plural': 'اضافة الطلاب',
            },
        ),
        migrations.CreateModel(
            name='SchoolSupplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='   الأداة المدرسية')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف   الأداة المدرسية')),
                ('source', models.CharField(choices=[('وزارة التربية والتعليم', 'وزارة التربية والتعليم'), ('مورد خارجي', 'مورد خارجي')], max_length=50, verbose_name='مصدر التوريد')),
                ('in_quantity', models.IntegerField(default=0, verbose_name='الكمية الواردة')),
                ('live_quantity', models.IntegerField(default=0, verbose_name='الكمية الحالية')),
                ('term', models.CharField(choices=[('الترم الأول', 'الترم الأول'), ('الترم الثاني', 'الترم الثاني')], max_length=20, verbose_name='الترم الدراسي')),
                ('received_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الاستلام')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'ادوات   مدرسية',
                'verbose_name_plural': 'الادوات المدرسية',
            },
        ),
        migrations.AddField(
            model_name='schoolbooklet',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.supplier', verbose_name='المورد'),
        ),
        migrations.AddField(
            model_name='notebooktype',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.supplier', verbose_name='المورد'),
        ),
        migrations.AddField(
            model_name='book',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.supplier', verbose_name='المورد'),
        ),
        migrations.AlterUniqueTogether(
            name='classlevel',
            unique_together={('stage', 'name', 'academic_year')},
        ),
        migrations.CreateModel(
            name='BookDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=20, verbose_name='رقم الإيصال')),
                ('delivery_date', models.DateField(verbose_name='تاريخ التوزيع')),
                ('distribution_status', models.CharField(choices=[('جزئي', 'توزيع جزئي'), ('كامل', 'توزيع كامل')], default='كامل', max_length=20, verbose_name='حالة التوزيع')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='اسم المستلم')),
                ('books', models.ManyToManyField(blank=True, to='store.book', verbose_name='الكتب المسلمة')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.classlevel', verbose_name='الصف الدراسي')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.classroom', verbose_name='الفصل الدراسي')),
                ('notebooks', models.ManyToManyField(blank=True, to='store.notebooktype', verbose_name='الكراسات المسلمة')),
                ('booklets', models.ManyToManyField(blank=True, to='store.schoolbooklet', verbose_name='البوكليتات المسلمة')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.stage', verbose_name='المرحلة الدراسية')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'توزيع الكتب والكراسات والبوكليتات',
                'verbose_name_plural': 'توزيع الكتب والكراسات والبوكليتات',
                'unique_together': {('student', 'delivery_date', 'receipt_number')},
            },
        ),
        migrations.AddConstraint(
            model_name='schoolsupplies',
            constraint=models.UniqueConstraint(fields=('name', 'description'), name='unique_school_supplies'),
        ),
        migrations.AddConstraint(
            model_name='schoolbooklet',
            constraint=models.UniqueConstraint(fields=('title', 'booklet_edition', 'stage', 'class_level'), name='unique_booklet'),
        ),
        migrations.AddConstraint(
            model_name='notebooktype',
            constraint=models.UniqueConstraint(fields=('name', 'size'), name='unique_notebook_type'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('title', 'source', 'term', 'stage', 'class_level'), name='unique_book_per_class'),
        ),
    ]
