# Generated by Django 5.0.6 on 2024-06-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlevel',
            name='name',
            field=models.CharField(choices=[('تمهيدى', 'تمهيدى'), ('KG1', 'KG1'), ('KG2', 'KG2'), ('PRIM 1', 'PRIM 1'), ('PRIM 2', 'PRIM 2'), ('PRIM 3', 'PRIM 3'), ('PRIM 4', 'PRIM 4'), ('PRIM 5', 'PRIM 5'), ('PRIM 6', 'PRIM 6'), ('PREP 1', 'الصف الاعدادى الأول'), ('PREP 2', 'الصف الثاني الاعدادى '), ('PREP 3', 'الصف الثالث الاعدادى '), ('SEC 1', 'الصف الأول الثانوي '), ('SEC 2', 'الصف الثاني الثانوي '), ('SEC 3', 'الصف الثالث الثانوي ')], max_length=50, verbose_name='اسم الصف الدراسي'),
        ),
    ]
