# Generated by Django 5.0.6 on 2024-06-14 17:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_classlevel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookletOutstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المستلم')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية ')),
                ('date', models.DateField(verbose_name='تاريخ الصرف')),
                ('booklet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.schoolbooklet', verbose_name='البوكليت')),
            ],
            options={
                'verbose_name': 'صرف بوكليت',
                'verbose_name_plural': 'صرف بوكليت',
            },
        ),
    ]
