# Generated by Django 5.0.6 on 2024-06-14 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_bookletoutstore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'verbose_name': 'السنة', 'verbose_name_plural': 'السنة الدراسية'},
        ),
    ]
